channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - bottleneck
  - fastapi
  - gcsfs
  - google-cloud-bigquery
  - google-cloud-bigquery-storage
  - google-cloud-pubsub
  - google-cloud-storage
  - matplotlib-base
  - numpy
  - numexpr
  - pandas
  - photutils
  - pip
  - pyarrow
  - scikit-learn
  - scipy
  - uvicorn
  - pip:
      - "git+https://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils[config,images,social]"
      - google-cloud-firestore
